# Generated by Django 6.0.3 on 2026-04-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="measurementitem",
            name="custom_item_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="measurementitem",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="description",
            field=models.TextField(),
        ),
    ]
