# Generated by Django 5.2.3 on 2026-04-14 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="quotation",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("full", "Full Day"),
                    ("half", "Half Day"),
                    ("leave", "Leave"),
                    ("out", "Out of City Work"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="measurementitem",
            name="custom_item_name",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="orderpayment",
            name="amount",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderpayment",
            name="date",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="custom_terms",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quotation",
            name="date",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="terms_and_conditions",
            field=models.TextField(blank=True, default=" "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="quotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.quotation",
            ),
        ),
        migrations.AlterField(
            model_name="quotationterm",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="quotationterm",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotation_terms_on_term",
                to="core.termcondition",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["employee", "date"], name="core_attend_employe_7ab622_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer"], name="core_order_custome_bed536_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="core_order_created_912d27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["quotation"], name="core_order_quotati_23c4b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "created_at"], name="core_order_custome_dab258_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderpayment",
            index=models.Index(fields=["order"], name="core_orderp_order_i_58f77c_idx"),
        ),
        migrations.AddIndex(
            model_name="orderpayment",
            index=models.Index(fields=["date"], name="core_orderp_date_03fa73_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["customer"], name="core_quotat_custome_46521a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["date"], name="core_quotat_date_a647b0_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["customer", "date"], name="core_quotat_custome_6352f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotationterm",
            index=models.Index(
                fields=["quotation"], name="core_quotat_quotati_e70620_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotationterm",
            index=models.Index(fields=["term"], name="core_quotat_term_id_4a4db4_idx"),
        ),
    ]
