# Generated by Django 5.2.3 on 2026-04-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_measurement_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurementitem",
            name="custom_item_name",
            field=models.TextField(blank=True, default=""),
        ),
    ]
