# Generated by Django 5.2.3 on 2026-04-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_measurementitem_custom_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="custom_terms",
            field=models.TextField(blank=True, default=""),
        ),
    ]
