# Generated by Django 5.2.3 on 2026-05-22 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_quotation_include_payment_details_paymentdetails_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "logo_path",
                    models.CharField(
                        blank=True,
                        help_text="Static path or filename to company logo (e.g. 'logo.png' or 'static/jglogo.png')",
                        max_length=255,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=100)),
                ("email", models.CharField(blank=True, max_length=200)),
                ("gstin", models.CharField(blank=True, max_length=32)),
                ("bank_details", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="quotation",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to="core.company",
            ),
        ),
    ]
