# Generated by Django 5.2.3 on 2026-05-25 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_orderpayment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["service_code", "name"]},
        ),
        migrations.RemoveField(
            model_name="measurementitem",
            name="custom_item_name",
        ),
        migrations.RemoveField(
            model_name="measurementitem",
            name="item_type",
        ),
        migrations.RemoveField(
            model_name="measurementitem",
            name="price_per_unit",
        ),
        migrations.RemoveField(
            model_name="measurementitem",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="measurementitem",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="quotationitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price",
        ),
        migrations.AddField(
            model_name="measurementitem",
            name="area",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="measurementitem",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="measurementitem",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="measurementitem",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name="measurementitem",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="measurementitem",
            name="service_code",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="measurementitem",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="measurementitem",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotation_items",
                to="core.service",
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="service_code",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="default_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="service_images/"),
        ),
        migrations.AddField(
            model_name="service",
            name="service_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="unit",
            field=models.CharField(default="Sq Ft", max_length=50),
        ),
        migrations.AddField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="measurementitem",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="unit",
            field=models.CharField(default="Sq Ft", max_length=50),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
