# Generated by Django 5.2.3 on 2026-05-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_service_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurementitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("size", "Size based"),
                    ("length", "Length / RFT"),
                    ("nos", "Count / Nos"),
                ],
                db_index=True,
                default="size",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="measurementitem",
            name="unit",
            field=models.CharField(db_index=True, default="Sq Ft", max_length=20),
        ),
    ]
