# Generated by Django 5.2.3 on 2026-05-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_compat_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationitem",
            name="custom_item_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
