# Generated by Django 5.2.3 on 2026-05-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_quotationitem_custom_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_name",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
