# Generated by Django 5.2.3 on 2026-05-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_service_service_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
    ]
