# Generated by Django 5.2.3 on 2026-06-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="tax_type",
            field=models.CharField(
                choices=[("none", "Without Tax"), ("gst", "GST"), ("igst", "IGST")],
                default="none",
                max_length=20,
            ),
        ),
    ]
