# Generated by Django 5.2.3 on 2026-06-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_quotation_tax_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationitem",
            name="manual_quantity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="raw_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
    ]
