# Generated by Django 5.2.3 on 2026-06-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_quotationitem_manual_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="services/"
            ),
        ),
    ]
