# Generated by Django 5.2.3 on 2026-06-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_service_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="paymentdetails",
            name="account_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Custom name like "Shop Account"',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="paymentdetails",
            name="account_number",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="paymentdetails",
            name="holder_name",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="paymentdetails",
            name="phone_number",
            field=models.CharField(blank=True, db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="paymentdetails",
            name="upi_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
