# Generated by Django 5.2.3 on 2026-06-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_company_phone_alter_customer_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="customer_gstin",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
