# Generated by Django 5.2.3 on 2026-09-10 07:45

from django.db import migrations, models


def populate_missing_service_codes(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    used_codes = set(Service.objects.exclude(service_code__isnull=True).exclude(service_code='').values_list('service_code', flat=True))
    for service in Service.objects.filter(models.Q(service_code__isnull=True) | models.Q(service_code='')).iterator():
        service.service_code = f'SVC-{service.pk}'
        suffix = 1
        while service.service_code in used_codes:
            service.service_code = f'SVC-{service.pk}-{suffix}'
            suffix += 1
        used_codes.add(service.service_code)
        service.save(update_fields=['service_code'])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_measurementitem_custom_item_name"),
    ]

    operations = [
        migrations.RunPython(populate_missing_service_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="service",
            name="service_code",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
